---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-security-profile-operator-py39
        - k8sapp-security-profile-operator-pylint
        - k8sapp-security-profile-operator-flake8
        - k8sapp-security-profile-operator-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-security-profile-operator-py39
        - k8sapp-security-profile-operator-pylint
        - k8sapp-security-profile-operator-flake8
        - k8sapp-security-profile-operator-metadata
    post:
      jobs:
        - stx-security-profiles-operator-app-upload-git-mirror

- job:
    name: k8sapp-security-profile-operator-py39
    parent: openstack-tox-py39
    description: |
            Run py39 test for k8sapp_security_profiles_operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-security-profiles-operator/*
    vars:
      tox_extra_args: -c python3-k8sapp-security-profiles-operator/k8sapp_security_profiles_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-security-profile-operator-metadata
    parent: tox
    description: |
            Run metadata test for k8sapp_security_profiles_operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-security-profiles-operator/k8sapp_security_profiles_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-security-profile-operator-pylint
    parent: tox
    description: |
            Run pylint test for k8sapp_security_profiles_operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-security-profiles-operator/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-security-profiles-operator/k8sapp_security_profiles_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-security-profile-operator-flake8
    parent: tox
    description: |
            Run flake8 test for k8sapp_security_profiles_operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-security-profiles-operator/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-security-profiles-operator/k8sapp_security_profiles_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-security-profiles-operator-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/app-security-profiles-operator to
      github.com/starlingx/app-security-profiles-operator
    vars:
      git_mirror_repository: starlingx/app-security-profiles-operator
    secrets:
      - name: git_mirror_credentials
        secret: stx-app-security-profiles-operator-github-secret3
        pass-to-parent: true

- secret:
    name: stx-app-security-profiles-operator-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - TKXzoC1fgZdpB7TIh5OuX0pSuWVZGXnQKCZ40gaOV0XDPBbDbX0VHFtaExEFPr5ByhXKv
          hdfZEYHgamFxdPlAsNbC+etlYfnFRBFKfS0lz0rPp4gm03LtVyo/KibssxQC2h5GODz6j
          0VRdgx8x2OVHA02VkGBFJjEOfDh2IlDdSLQoY1KDpt3K5QASbz5g9Wc25a3ZPgqgWIQ1V
          mQ5BBqzAoVfQiWYpmOoW36bJxMXHe6gpd20Fkaf47UjIo+SZiXO/ZPqxB8/oD4Uoh99tf
          kE5xTEeBmPGaAflRPpRW/VejP4jNxngVYmEM68rnVCq+FWl9PQUC2YZK0Uz1FydiZK1M0
          GZt5fpiz46zr43hb3RDmeEkVq1mBKnatLuxTM+37PeT2SV9zGQUWqv5j+WHSTFpT7HSla
          TeqU8170OaYbP5nsSg3xvNGPErfZlunYL/vM1ThC8UOqV7+LPPIUm6pQxAxFKegn0rejx
          YpqilN0PRyLeD0CCcEdMcL4ruukKqvdSYlsMF1Rj8zctLH9XuhDq7K008Lu2kpwoCBRvF
          t3jPpC+Iv1VBl9G+lm9wbtN+cr6TS4ZzZLfKRuqkLrztZHj9F0tUa18EE7Pg3h8Aa3XLT
          pLAHFEPXEXbqGoU8XB8nZyvjKGjK9bcI6Q6wY0b8GWFVUJ1cmoIraaQrZYLYP4=
        - CXEuiWdDpmdPc3K1m1Ob3vm7vGkLH0WKHupIZ4QbluIHFOIz73XhBAmhIw8ZO4yI/t0PZ
          dLe2Kn3+bE1GTU6Jp9dqFxNc/xhtOhExeoYO8iNnCPrTj6xpacNUKLUsemkAKUzKsM4tR
          ULA1gajnUSd8CTDHISHbkMDN+caJO8w+N1JHIlwvlKvETgztwE0Zjd8geRUvRuWtfVjI/
          nKmqRGNaIJa8fg8w65aSPFOZ9cpV6t33CgfcG6AqwxnyYDhOY8TPJtyV9gCG2ouUyvcgg
          7brEJ4L9Slz1COaRwmFH6TTvvrTNQJXE4RYVpV1NNWSI+XwKcSO3v9MFAcbLT0Neu4gcv
          qzXyJ/4oFqqiiHLG50RXHH9gAW/+5zPHKNejlrB72S00h87rP4aHquW/Txm0uhyCZzrf4
          wBiErcF774EEbsC6u9MUr/owKADAspc/OwPYAfksenl8uyY8o1mf/30U0GgNkDLOKQYNx
          fudzO9tr4lxgFWhNxW/GIl4bQrBYMEFMDgr28YkipAVY/NvfRzA+4024vPfNJAsG8TKpi
          ue3GA2y87NchYfB6oE8qrdkq02zXcYHbtmvE8Ofkm0JPcTLhNFgiPTjk+LdrOwC18xfsV
          9NQZn58Mwm6pqSoHDaO+LuEDe6whzLbGSCql97/cf7G3sfGPLFvTLRDsKL9rNE=
        - ApN25LWbclc8/UG4iS1rJhqq3r7OL1cTDi5YLu7UlCQRA9UshZGJZP1ePnIiQ083OvKiQ
          OOIWNjH5ovRhmSp7SAMjxzMX5U3nP4BE7aDPLf22eSa2qDe3j1239QHf6KNaR9bQzRV06
          OMNPByGmLbGNb0Zq/ZfNiUZBlkEd/kyZn5ZQNv64DxJN4D3Hy+Z4kymN6zD61p1KLnOKw
          gu+mRau+BwmmBj4mdp0fH9SXkjatCVnvzLm0NEX5ZrNKUabvc4bcBroqQgREyrMbmRmTQ
          3sqDFFfdtc0WY2VvtfrwW+EvMrexUy1xmG1Fjj97t+vvcyFN/mfjSoMo/WUI40u3/6ULc
          iCxhS4rGKyTgq4K2sAc5RagMdIyFy3V5o7kGrCZypnZB8dyb29IoeRocoSrB/ms+GGBBW
          kVYFFAiDPiZW7yP2VQNiz3ozOq9D3iyyZ3XfDJ2BaBz1TMhiw+aY/FUwDrMxKRuSzZHKf
          1q1iGldFldzJJnGy+JZwuGHe7IDVzRTMn2FYMfg6VVlz7d3GDwJgs4Ubsy/+VtZyuhz6L
          ygP81ZBaHz+s0Rn5b2uvelBA7ZroFdK4Ssizw+LJ+xAAdMsD1h8U0UQIJNWUEydWNTM0l
          zLvhsoruwCzi1/kToT5LrxXuxXTJ1VWEJD7pPQa1h3WjJqwdLPxwBtQxchDEzo=
        - tzRpDa/8Ad2DobHnh3J7RP3KVTQSXu3O79Jvp7f4P7DMUhbW1oLIZuIk8tgznOHwK/FxK
          imQ1X1uR4aXX/2bYGDWWzI0GeMK6SKi7Tbfw9HxUsm4obhnQN36nFa3pUQo2dQoulUAGb
          xI8ocCMRul2IHv0ySgBBhDUZg5XG3+P/ikCX3gdGaRlxQGvJryLIUqXW6GJEdUY+JhaN8
          L4ToHZe61my1VFhXrXUI9eKLE9aTmIyvZ+xEaEJID3SA8il6VCfZDCCESBgokC0vntJ3D
          ipiMo0IC4oQbXM0Gi6lsXpIt+zZGozE2nxRZnkdMXV07w+pZwZiUcSr+ehghNa04NHLk9
          Xti99nurIsbmH3cdmI9JLi3QsX6ZW/nWlBJ662zQQbsUqHlx7x5xKAWK6Bnfj1EabTHXU
          BFqX6vCbxVkSxfpv6kM82tGbLYgUJQZQ1ZBF92mQ2KXEkbVCREbL39nIgfunLmekccWbb
          pqh5LH6qYe6JqoYPhZzMC2fieDK6TOZYPs3kaKFwYjvU3n5pzFtrd54Iq9RU3iqGlGxul
          eYeO8jDeqAsQxo9GMBc75eLmqE0yK6X7CvIwSAgvPV/q3n41ucu2RdF0ZX9y24BOB9ZDK
          fDl5AlH8UQ+oQgmt/kS6QNI5Qiyqa3d8xxnHZ6vEz3KVdeLfXIjGSuzSVVBEhY=
        - NdXdxWl342gdlVgrr8nxDh0ya7udRWK6rX6mIaH32pbLbwotMKAl8Kmpsu6W6dc18hJRK
          8Akiq6jRkuyW6MwM7Iu06OGDXIusrvNcEmHBFt0/h4TkdZ4gZ2wo+rHetV+XchKQ8FQXF
          Y0uRz2e8yR73VaeGZumZNzFHlyZxbzemlFwnRYrqXSTgilGA8FORx5gt+feYk7FAkd1X+
          PmBJK+UhC1kEwxmst4y/vfSyAJ7FAtdth648fQecHVpgS+CB2SaUggXjAnSSSoXYBkrY5
          OaDagOle2rDBUtDzI/U/gABqR3r+o5IwMlPe1AaYuRY2U84HnLt2eAARo3TVQuibqu20g
          tpBLgyKLa9OPCV6zIXjSS/Xy+mB9mk+PKYq7LnjrBXzY5WovDKi05VEX1g9KUdh29AmOo
          PJiwU63/ZEuP5vobzBQ9eUsdrdAwtoXB1j/ZV/wmWc3xj5FXiMEScGhE6tL3aMF/2wlnh
          cb6S9iPQSW5NZXATgOCeP+nkEVFzEpzAIbeOwyjxbNXZOMbqnHc8yGbgp+KeJQEboYeJj
          UFAY/w9ynaX1iLGDrFpFFrYHZJ8p0B4pjxvLcjkB0UgIKJZ6whXqRiUEoRvDykmXlptcB
          RZLyDYdmpuSFk20ffLHBCSyNuoBTTtVbs85U4lH6HiyGdx3L357/Y11jkjhdis=
        - Si1SeyhvvsowjG9khrG6N8ogb0v+XZe6kzpXNYgN1ohQhpxnlwD+raBj2pgCzduoPtP5Z
          G3CpSgRErF12BEyHLkwld8uyjist5ajg+Xt7palZ3ZgJ9bun/dxZtof0wgQSfH4j9RCmw
          diyAs50xnG0yZmjixiZbnCdYPcK0piB0dw9OC9u0+Vae86Mz0OUmIcy4b/LIPYPWDSMy1
          7QIc6h3U1m2/ZNqYcwEByJQXzAsyhKQucgqTCGQYEUSsASV051D4JoIxEQB+sSsimTj8i
          ZjYxGm9308Y7l9ujbhY+sNq0DHYqco6ipf8nvZlPDwNQjFi4/0rt/SHcI+mk4w0sLvnDM
          FEv85eUGWMY19zdjQcwwYK2IaHTl/9DBdkbvl7XpcvjBfcyePkeLQlZBYqD0H0h46U8pQ
          BKhg7fqJRJr168GyGKu6KdR7aeALaXogh9YfLuYb30blG6ul+ni1AVUfuxKYwhIK9bux8
          rBw8iw0/12DEQOz9uMA5o268y/GtWi2btxAyQIbDZGHQx07OGwNmsqaEpGli8SwgN3pQt
          NZCXy3gw32KyUQKGZKnHQMcBufUqFHQgkdK4ggZs+FpGnWphP0iJc4QmVuUz98pNEwbZC
          TyGzyUrox3bemt00GO43l5Sxn83jsY+hs+ox0BAvnCGcSezcsk/1CPghMg8+go=
        - ca7UXBXZUd7OXCxUAYt3AXxW0/AmuhvBrRSxYJd+ybmrq1F3tigi3dEdmBBTwp4nUyj4f
          0GXLSm524h8lXrUEWYniKplK9Xdwc2WbwdJhxhQl6PB1UNY8evNOGYDTtyf/RBi6kRPhY
          hG+fBlDdAMmvXeROlb2XPn9hYQWl7nBalXQgHSs3xULnqORudHh1qCpBjiKs44yXi55dT
          TFAKNr6OfBLB6axY+2Uyl2RWyWP6yllv68d3O2nRfswYFzzrSu8joDkeNTLQPgbT1tTKJ
          O9pOZZzk+M8JYUE2EU9tkcFeU8YG+mzAgQFqQEwDIe45ogahG9psRs+rTzDIIPKQJ0ZPu
          HRzO8iBabMfIi/IDidgyZE1Az4xgbvcmp8KYYoWbacuYFcZhioIwX2mmAObs0LvozspNh
          h5FxZMyKLuGNkvZzIaPnrOPm1A74zpmyXH+VutkExYmnT3gKyV4ThoU2mMVtDtR3Cx/Ey
          8QGNv0WAn4kl38oQ+BL08pveMJIDUlPv173Te4ObtXbkbG4Bb0i+e7h5/JAu/W5JDZgMv
          eprqRbx38z4KoQ7kZRreHut8uttNt7hPAnbbzxfnW7XaWwvWV4Mb4XtpCx0F235gIYwHa
          RqIAOAhofHypYZvbolMuo6UqQZVDSR8lODA27NDL/Alova6dhm310a3gZUe99Q=
