#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: security-profiles-operator
  labels:
    chart_group: security-profiles-operator-charts
spec:
  releaseName: security-profiles-operator
  chart:
    spec:
      chart: security-profiles-operator
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: spo-static-overrides
      valuesKey: spo-static-overrides.yaml
    - kind: Secret
      name: spo-system-overrides
      valuesKey: spo-system-overrides.yaml
